<a href="https://colab.research.google.com/github/JagdeepMohanty/VALUE_ADDED_COURSE/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
a1 = np.array([1,2,3])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [ ]:
print(a1), a1.shape , a1.ndim, a1.dtype ,a1.size, type(a1)

[1 2 3]


(None, (3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
print(a2), a2.shape , a2.ndim, a2.dtype ,a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
print(a3), a3.shape , a3.ndim, a3.dtype ,a3.size, type(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(None, (2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [ ]:
"Creating Array "
np.array()
np.ones()
np.zeros()
np.random.rand(5,3)
np.random.randint(10,size=(7,2))

In [ ]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones = np.ones((7,4))
ones.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
ones = np.ones((10,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
range_array = np.arange(156,202,2)
range_array

array([156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
range_array = np.arange(1,101,2)
range_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
range_array = np.arange(0,101,2)
range_array

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[2, 1, 9, 0, 6],
       [9, 5, 3, 0, 6],
       [9, 1, 5, 7, 3]])

In [ ]:
np.random.random((3,5))


array([[0.71918564, 0.46748482, 0.76910761, 0.39170451, 0.00220502],
       [0.40411784, 0.23377328, 0.33836322, 0.28773084, 0.24014989],
       [0.42764241, 0.09964301, 0.21431882, 0.98235906, 0.22940777]])

In [ ]:
np.random.seed(5)
random_array = np.random.randint(100,size=(6,3))
random_array

array([[99, 78, 61],
       [16, 73,  8],
       [62, 27, 30],
       [80,  7, 76],
       [15, 53, 80],
       [27, 44, 77]])

In [65]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(a%b)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[1 1 1]
[ 1  4 27]
[0 0 0]


a1 = np.array([1,2,3])