<a href="https://colab.research.google.com/github/JagdeepMohanty/VALUE_ADDED_COURSE/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [4]:
import numpy as np

In [6]:
print(np.__version__)

2.0.2


In [9]:
a1 = np.array([1,2,3])

In [11]:
a2 = np.array([[1,2,3],[4,5,6]])

In [13]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [21]:
print(a1), a1.shape , a1.ndim, a1.dtype ,a1.size, type(a1)

[1 2 3]


(None, (3,), 1, dtype('int64'), 3, numpy.ndarray)

In [18]:
print(a2), a2.shape , a2.ndim, a2.dtype ,a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [22]:
print(a3), a3.shape , a3.ndim, a3.dtype ,a3.size, type(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(None, (2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [ ]:
"Creating Array "
np.array()
np.ones()
np.zeros()
np.random.rand(5,3)
np.random.randint(10,size=(7,2))

In [30]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
ones = np.ones((7,4))
ones.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
ones = np.ones((10,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])